export const VIDEO_LIST_REQUEST = "VIDEO_LIST_REQUEST";
export const VIDEO_LIST_SUCCESS = "VIDEO_LIST_SUCCESS";
export const VIDEO_LIST_FAIL = "VIDEO_LIST_FAIL";
export const VIDEO_LIST_RESET = "VIDEO_LIST_RESET";

export const VIDEO_GET_REQUEST = "VIDEO_GET_REQUEST";
export const VIDEO_GET_SUCCESS = "VIDEO_GET_SUCCESS";
export const VIDEO_GET_FAIL = "VIDEO_GET_FAIL";
export const VIDEO_GET_RESET = "VIDEO_GET_RESET";

export const VIDEO_ADD_REQUEST = "VIDEO_ADD_REQUEST";
export const VIDEO_ADD_SUCCESS = "VIDEO_ADD_SUCCESS";
export const VIDEO_ADD_FAIL = "VIDEO_ADD_FAIL";
export const VIDEO_ADD_RESET = "VIDEO_ADD_RESET";

export const VIDEO_UPDATE_REQUEST = "VIDEO_UPDATE_REQUEST";
export const VIDEO_UPDATE_SUCCESS = "VIDEO_UPDATE_SUCCESS";
export const VIDEO_UPDATE_FAIL = "VIDEO_UPDATE_FAIL";
export const VIDEO_UPDATE_RESET = "VIDEO_UPDATE_RESET";

export const VIDEO_DELETE_REQUEST = "VIDEO_DELETE_REQUEST";
export const VIDEO_DELETE_SUCCESS = "VIDEO_DELETE_SUCCESS";
export const VIDEO_DELETE_FAIL = "VIDEO_DELETE_FAIL";
export const VIDEO_DELETE_RESET = "VIDEO_DELETE_RESET";

export const VIDEO_LIKE_REQUEST = "VIDEO_LIKE_REQUEST";
export const VIDEO_LIKE_SUCCESS = "VIDEO_LIKE_SUCCESS";
export const VIDEO_LIKE_FAIL = "VIDEO_LIKE_FAIL";
export const VIDEO_LIKE_RESET = "VIDEO_LIKE_RESET";

export const VIDEO_DISLIKE_REQUEST = "VIDEO_DISLIKE_REQUEST";
export const VIDEO_DISLIKE_SUCCESS = "VIDEO_DISLIKE_SUCCESS";
export const VIDEO_DISLIKE_FAIL = "VIDEO_DISLIKE_FAIL";
export const VIDEO_DISLIKE_RESET = "VIDEO_DISLIKE_RESET";

export const VIDEO_COMMENT_REQUEST = "VIDEO_COMMENT_REQUEST";
export const VIDEO_COMMENT_SUCCESS = "VIDEO_COMMENT_SUCCESS";
export const VIDEO_COMMENT_FAIL = "VIDEO_COMMENT_FAIL";
export const VIDEO_COMMENT_RESET = "VIDEO_COMMENT_RESET";

export const VIDEO_COMMENT_UPDATE_REQUEST = "VIDEO_COMMENT_UPDATE_REQUEST";
export const VIDEO_COMMENT_UPDATE_SUCCESS = "VIDEO_COMMENT_UPDATE_SUCCESS";
export const VIDEO_COMMENT_UPDATE_FAIL = "VIDEO_COMMENT_UPDATE_FAIL";
export const VIDEO_COMMENT_UPDATE_RESET = "VIDEO_COMMENT_UPDATE_RESET";

export const VIDEO_COMMENT_DELETE_REQUEST = "VIDEO_COMMENT_DELETE_REQUEST";
export const VIDEO_COMMENT_DELETE_SUCCESS = "VIDEO_COMMENT_DELETE_SUCCESS";
export const VIDEO_COMMENT_DELETE_FAIL = "VIDEO_COMMENT_DELETE_FAIL";
export const VIDEO_COMMENT_DELETE_RESET = "VIDEO_COMMENT_DELETE_RESET";

export const VIDEO_VIEW_COUNT_REQUEST = "VIDEO_VIEW_COUNT_REQUEST";
export const VIDEO_VIEW_COUNT_SUCCESS = "VIDEO_VIEW_COUNT_SUCCESS";
export const VIDEO_VIEW_COUNT_FAIL = "VIDEO_VIEW_COUNT_FAIL";
export const VIDEO_VIEW_COUNT_RESET = "VIDEO_VIEW_COUNT_RESET";
